//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUnknown
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HomeUnknownEntities : DbContext
    {
        public HomeUnknownEntities()
            : base("name=HomeUnknownEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Contents> tbl_Contents { get; set; }
        public virtual DbSet<tbl_Events> tbl_Events { get; set; }
        public virtual DbSet<tbl_Timelines> tbl_Timelines { get; set; }
        public virtual DbSet<tbl_relUserContent> tbl_relUserContent { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    
        public virtual ObjectResult<sp_sel_EventContent_Result> sp_sel_EventContent(Nullable<System.Guid> eventId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sel_EventContent_Result>("sp_sel_EventContent", eventIdParameter);
        }
    
        public virtual ObjectResult<sp_sel_TimelineEvents_SelectByTimeline_Result> sp_sel_TimelineEvents_SelectByTimeline(Nullable<System.Guid> timelineId)
        {
            var timelineIdParameter = timelineId.HasValue ?
                new ObjectParameter("TimelineId", timelineId) :
                new ObjectParameter("TimelineId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sel_TimelineEvents_SelectByTimeline_Result>("sp_sel_TimelineEvents_SelectByTimeline", timelineIdParameter);
        }
    
        public virtual ObjectResult<sp_sel_TimelineHome_Select_Result> sp_sel_TimelineHome_Select(Nullable<System.Guid> familyID)
        {
            var familyIDParameter = familyID.HasValue ?
                new ObjectParameter("FamilyID", familyID) :
                new ObjectParameter("FamilyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sel_TimelineHome_Select_Result>("sp_sel_TimelineHome_Select", familyIDParameter);
        }
    
        public virtual int sp_ins_EventContent(Nullable<System.Guid> eventId, string contentName, string contentText, Nullable<int> contentType, string contentURL)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(System.Guid));
    
            var contentNameParameter = contentName != null ?
                new ObjectParameter("ContentName", contentName) :
                new ObjectParameter("ContentName", typeof(string));
    
            var contentTextParameter = contentText != null ?
                new ObjectParameter("ContentText", contentText) :
                new ObjectParameter("ContentText", typeof(string));
    
            var contentTypeParameter = contentType.HasValue ?
                new ObjectParameter("ContentType", contentType) :
                new ObjectParameter("ContentType", typeof(int));
    
            var contentURLParameter = contentURL != null ?
                new ObjectParameter("ContentURL", contentURL) :
                new ObjectParameter("ContentURL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_EventContent", eventIdParameter, contentNameParameter, contentTextParameter, contentTypeParameter, contentURLParameter);
        }
    
        public virtual int sp_ins_TimelineEvent(Nullable<System.Guid> timelineId, string eventName, string eventLocation, Nullable<System.DateTime> eventYear)
        {
            var timelineIdParameter = timelineId.HasValue ?
                new ObjectParameter("TimelineId", timelineId) :
                new ObjectParameter("TimelineId", typeof(System.Guid));
    
            var eventNameParameter = eventName != null ?
                new ObjectParameter("EventName", eventName) :
                new ObjectParameter("EventName", typeof(string));
    
            var eventLocationParameter = eventLocation != null ?
                new ObjectParameter("EventLocation", eventLocation) :
                new ObjectParameter("EventLocation", typeof(string));
    
            var eventYearParameter = eventYear.HasValue ?
                new ObjectParameter("EventYear", eventYear) :
                new ObjectParameter("EventYear", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_TimelineEvent", timelineIdParameter, eventNameParameter, eventLocationParameter, eventYearParameter);
        }
    
        public virtual ObjectResult<sp_sel_SingleMedia_Result> sp_sel_SingleMedia(Nullable<System.Guid> contentId)
        {
            var contentIdParameter = contentId.HasValue ?
                new ObjectParameter("ContentId", contentId) :
                new ObjectParameter("ContentId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sel_SingleMedia_Result>("sp_sel_SingleMedia", contentIdParameter);
        }
    
        public virtual ObjectResult<string> sp_sel_UserPicture(Nullable<System.Guid> contentId)
        {
            var contentIdParameter = contentId.HasValue ?
                new ObjectParameter("ContentId", contentId) :
                new ObjectParameter("ContentId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_sel_UserPicture", contentIdParameter);
        }
    }
}
