//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUnknown
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HomeUnknownEntities : DbContext
    {
        public HomeUnknownEntities()
            : base("name=HomeUnknownEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Contents> tbl_Contents { get; set; }
        public virtual DbSet<tbl_Events> tbl_Events { get; set; }
        public virtual DbSet<tbl_Timelines> tbl_Timelines { get; set; }
    
        public virtual ObjectResult<sp_sel_EventContent_Result> sp_sel_EventContent(Nullable<System.Guid> eventId)
        {
            var eventIdParameter = eventId.HasValue ?
                new ObjectParameter("EventId", eventId) :
                new ObjectParameter("EventId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sel_EventContent_Result>("sp_sel_EventContent", eventIdParameter);
        }
    
        public virtual ObjectResult<sp_sel_TimelineEvents_SelectByTimeline_Result> sp_sel_TimelineEvents_SelectByTimeline(Nullable<System.Guid> timelineId)
        {
            var timelineIdParameter = timelineId.HasValue ?
                new ObjectParameter("TimelineId", timelineId) :
                new ObjectParameter("TimelineId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sel_TimelineEvents_SelectByTimeline_Result>("sp_sel_TimelineEvents_SelectByTimeline", timelineIdParameter);
        }
    
        public virtual ObjectResult<sp_sel_TimelineHome_Select_Result> sp_sel_TimelineHome_Select(Nullable<System.Guid> familyID)
        {
            var familyIDParameter = familyID.HasValue ?
                new ObjectParameter("FamilyID", familyID) :
                new ObjectParameter("FamilyID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sel_TimelineHome_Select_Result>("sp_sel_TimelineHome_Select", familyIDParameter);
        }
    }
}
