//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUnknown
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Contents
    {
        public System.Guid Content_PK { get; set; }
        public string ContentName { get; set; }
        public System.Guid Event_PK { get; set; }
        public string ContentText { get; set; }
        public int ContentType { get; set; }
        public string ContentURL { get; set; }
    }
}
