//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUnknown
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_relUserContent
    {
        public System.Guid Content_PK { get; set; }
        public System.Guid User_PK { get; set; }
    }
}
