//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUnknown
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Events
    {
        public System.Guid Event_PK { get; set; }
        public string EventName { get; set; }
        public System.Guid Timeline_PK { get; set; }
        public string EventLocation { get; set; }
        public System.DateTime EventYear { get; set; }
    
        public virtual tbl_Events tbl_Events1 { get; set; }
        public virtual tbl_Events tbl_Events2 { get; set; }
    }
}
