//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeUnknown
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Timelines
    {
        public System.Guid Timeline_PK { get; set; }
        public System.DateTime BeginningYear { get; set; }
        public string PictureURL { get; set; }
        public string TimelineName { get; set; }
    }
}
